config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  root 'search#index'
  get 'search' => "search#index", :as => :search
  resources :players
 	resources :searches
end

app/models/search.rb
class Search 
	attr_accessor :args

  def initialize(*params)
    @args = Hash.new.tap do |a|
      params.each do |p|
        p.each do |k,v|
          a[k.to_sym] = v
        end
      end
    end
  end

  def url_builder(options={})
    new_args = args.merge(options).delete_if {|k,v| true if ([:action,:controller,:page,:per_page,:account_id].index(k) || v.blank?) }
    new_args[:per_page] = options[:per_page] if options[:per_page]
    link = ""

    if options[:tags]
      link << "/#{options[:tags].map {|t| t.slug }.join("+")}"
    elsif new_args[:tags]
      link << "/#{new_args[:tags]}"
    else
      link << "/search"
    end

    new_args = new_args.delete_if {|k| true if (k == :tags ) }

    link << "?#{new_args.to_query}" unless new_args.to_query.blank?
    link 
  end

  def facet_position
    r = []
    r << {:name => "All", :url => url_builder(:position => nil), :active => (args[:position] ? false : true)}
    r << {:name => "SP",
          :url => url_builder(:position => "SP"), :active => (args[:postion] == "SP" ? true : false)}
    r << {:name => "RP",
          :url => url_builder(:position => "RP"), :active => (args[:postion] == "RP" ? true : false)}
    r << {:name => "1st Baseman",
          :url => url_builder(:position => "1b"), :active => (args[:postion] == "1b" ? true : false)}
    r << {:name => "2nd Baseman",
          :url => url_builder(:position => "2b"), :active => (args[:postion] == "2b" ? true : false)}
     r << {:name => "3rd Baseman",
          :url => url_builder(:position => "3b"), :active => (args[:postion] == "3b" ? true : false)}
    r
  end
  
  def facet_contract_remaining
    r = []
    r << {:name => "All", :url => url_builder(:years => nil), :active => (args[:position] ? false : true)}
    r << {:name => "Pending Free Agent",
          :url => url_builder(:years => "1"), :active => (args[:postion] == "1" ? true : false)}
    r << {:name => "2 Years Left",
          :url => url_builder(:years => "2"), :active => (args[:postion] == "2" ? true : false)}
    r << {:name => "3 Years Left",
          :url => url_builder(:years => "3"), :active => (args[:postion] == "3" ? true : false)}
    r << {:name => "4 Years Left",
          :url => url_builder(:years => "4"), :active => (args[:postion] == "4" ? true : false)}
     r << {:name => "5 Years Left",
          :url => url_builder(:years => "5"), :active => (args[:postion] == "5" ? true : false)}
    r
  end


  def facet_salary
    r = []
    r << {:label => "All", :url => url_builder(salary_low: nil, salary_high: nil), :active => (args[:position] ? false : true)}
    r << {label: "Under $500,000",
          :url => url_builder(salary_low: 1, salary_high: 500000), :active => (args[:postion] == "SP" ? true : false)}
    r << {label: "$500,001 - $1,000,000",
          :url => url_builder(salary_low: 500000, salary_high: 1000000), :active => (args[:postion] == "RP" ? true : false)}
    r << {label: "$1,000,001 - $3,000,000",
          :url => url_builder(salary_low: 1000000, salary_high: 3000000), :active => (args[:postion] == "1b" ? true : false)}
    r << {label: "$3,000,000 - $5,000,000",
          :url => url_builder(salary_low: 3000000, salary_high: 5000000), :active => (args[:postion] == "2b" ? true : false)}
    r << {label: "$5,000,000 - $10,000,000",
          :url => url_builder(salary_low: 5000000, salary_high: 10000000), :active => (args[:postion] == "3b" ? true : false)}
    r << {label: "$10,000,000 - $15,000,000",
          :url => url_builder(salary_low: 10000000, salary_high: 15000000), :active => (args[:postion] == "1b" ? true : false)}
    r << {label: "$15,000,000 - $20,000,000",
          :url => url_builder(salary_low: 15000000, salary_high: 20000000), :active => (args[:postion] == "2b" ? true : false)}
     r << {label: "Over $20,000,000" ,
          :url => url_builder(salary_low: 20000000), :active => (args[:postion] == "3b" ? true : false)}
    r
  end

  def facet_outcomes
    r = []
    r << {label: "Probability of Home Run",
          :url => url_builder(outcome: "home_run"), :active => (args[:postion] == "home_run" ? true : false)}
    r << {label: "Probability of Strikeout",
          :url => url_builder(outcome: "strikeout"), :active => (args[:postion] == "strikeout" ? true : false)}
    r
  end



  def players
    return @players if @players
    unless player_query.nil?
	    @players = Player.search((args[:new] ? player_query_new : player_query))
	  end
    return @players
  end

  def player_query
    s = {:explain => false, :sort => [], :query => {"bool" => { "must" => [], "should" => [], "must_not" => [], "filter" => [] }}}

    if args[:position].blank?
	    s = {:explain => false, :sort => [], :query => {"bool" => { "must" => [], "should" => [], "must_not" => [], "filter" => [] }}}
    elsif args[:position] == "3b"
	    s[:query]["bool"]["filter"] << {:match => {:position => "5"}}
    elsif args[:position] == "SP"
    	s[:query]["bool"]["filter"] << {:match => {:position => "1"}}
    end

    
  	s[:query]["bool"]["filter"] << {range: {:salary => {gte: args[:salary_low].to_i }}} unless args[:salary_low].blank?
  	s[:query]["bool"]["filter"] << {range: {:salary => {lte: args[:salary_high].to_i }}} unless args[:salary_high].blank?
   
    return s
  end

  def cat

  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	def index
	  @search = Search.new(params, :per_page => (params[:per_page] ||= session[:per_page]))
    @pitch_data = Pitch.event_outcome_pitcher(params[:outcome])
    @pitcher1_data = @pitch_data.first
    @pitcher2_data = @pitch_data.last
    
    respond_to do |format|
      format.html
      format.js
    end
	end

	def search

  if params[:q].nil?
    @players = []
  else
    @players = Player.search params[:q]
  end
	end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_results.html.erb
<table class="table table-condensed">
	<tbody>
		<% @search.players.each do |player| %>
		  <tr>
	    	<td width="70"><%= image_tag(player.primary_photo_path, height: '138') %> </td>
		    <td>
					<strong><%= link_to player.name, player_path(player) %></strong> <small>/ <%= player.date_of_birth %> / SP / <%= number_to_currency(player.salary, :precision => 0) %></small>
						<div id="container_<%= player.id %>" style="height: 475px; max-width: 420px; margin: 0 auto"></div>
						<div><small>Data from 2013-2015 seasons; Source: Pitch f/x data</small></div>
						<div><small>[x feet, y feet : probability of <%= params[:outcome] %> for pitches in that location in percentage terms]</small></div>
				</td>
		  </tr>
		  <script>
			<% if player.id = 501957 %>	
				Highcharts.chart('container_501957', {

			    chart: {
			        type: 'heatmap',
			    },


			    title: {
			        text: 'Pitcher Heat Map',
			        align: 'left'
			    },


			    xAxis: {
				    	title: {
			            text: 'Feet from center of home plate'
			        },
			        labels: {

			            
			        },
			        minPadding: 0,
			        maxPadding: 0,

			        tickPositions: [-1.5,-1,-0.5,0,0.5,1,1.5],
			        tickWidth: 0.3,
			        min: -1.5,
			        max: 1.5
			    },

			    yAxis: {
			        title: {
			            text: 'Feet'
			        },
			        labels: {
			            
			        },
			        minPadding: 0,
			        maxPadding: 0,

			        tickPositions: [0, 1, 2, 3, 4, 5],
			        tickWidth: 1,
			        min: 0,
			        max: 5
			    },

			    colorAxis: {
			        stops: [
			            [0, '#3060cf'],
			            [0.5, '#fffbbc'],
			            [0.9, '#c4463a']
			        ],
			        min: 0
			    },

			 	  series: [{
			      borderWidth: 0.5,
			      data: <%= @pitcher1_data %>,
			      colsize: 0.28,
			      rowsize: 0.4,
			      tooltip: {
				    headerFormat: 'Probability ',
				    pointFormat: '{point.value} %'
					}, 
			    }]
				});
				<% end %>
				<% if player.id = 592332 %>
					Highcharts.chart('container_592332', {
					  chart: {
					      type: 'heatmap',
					  },


					  title: {
					      text: "Pitcher Heat Map ",
					      align: 'left'
					  },

					  xAxis: {	    	
						  	title: {
				            text: 'Feet from center of home plate'
				        },
					      labels: {
					          
					      },
					      minPadding: 0,
					      maxPadding: 0,

					      tickPositions: [-1.5,-1,-0.5,0,0.5,1,1.5],
					      tickWidth: 0.3,
					      min: -1.5,
					      max: 1.5
					  },

					  yAxis: {
					      title: {
					          text: 'Feet'
					      },
					      labels: {
					          
					      },
					      minPadding: 0,
					      maxPadding: 0,

					      tickPositions: [0, 1, 2, 3, 4, 5],
					      tickWidth: 1,
					      min: 0,
					      max: 5
					  },

					  colorAxis: {
					      stops: [
					          [0, '#3060cf'],
					          [0.5, '#fffbbc'],
					          [0.9, '#c4463a']
					      ],
					      min: 0
					  },

					  series: [{
					      borderWidth: 0.5,
					      data: <%= @pitcher2_data %>,
					      colsize: 0.28,
					      rowsize: 0.4,
				        tooltip: {
						    headerFormat: 'Probability ',
						    pointFormat: '{point.value} %'
						}, 

					  }]
					});
					<% end %>
			</script>
		<% end %>
	</tbody>
</table>

app/views/search/index.html.erb
<div style="clear:both"></div>
<div class="row">
	<div class ="span4">
	</div>
	<div class="span8">
		<div class="btn-group">
			<div class="dropdown">
			  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			    Position
			  </button>
			  <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
			    <% @search.facet_position.each do |position| %>
				    <button class="dropdown-item" type="button"><%= link_to position[:name], position[:url] %></button>
			    <% end %>
			  </div>
			</div>
			<div class="dropdown">
			  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			    Salary
			  </button>
			  <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
			    <% @search.facet_salary.each do |salary| %>
				    <button class="dropdown-item" type="button"><%= link_to salary[:label], salary[:url] %></button>
			    <% end %>

	  			<input class="span1" id="fee_low_box" list="fee_options" name="fee_low" placeholder="Min" size="50" style="margin-left:20px; width:95px" type="text"></input>
	  			<input class="span1" id="fee_high_box" list="fee_options2" name="fee_high" placeholder="Max" size="50" style="width:95px" type="text"></input>
			  </div>
			</div>
			<div class="dropdown">
			  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			    Contract
			  </button>
			  <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
				<% @search.facet_contract_remaining.each do |years| %>
				    <button class="dropdown-item" type="button"><%= link_to years[:name], years[:url] %></button>
			    <% end %>
			  </div>

			</div>
			<div class="dropdown">
			  <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			    Pitch Outcome
			  </button>
			  <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
				<% @search.facet_outcomes.each do |outcome| %>
				    <button class="dropdown-item" type="button"><%= link_to outcome[:label], outcome[:url] %></button>
			    <% end %>
			  </div>
			</div>
		</div>
		<%= render 'results' %>
	</div>
</div>